### ISSUE TITLE
Extra blank pages when element is taller than page

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#23]
Looks like extra pages are created *before* when there is an overflow page. It doesn't look like the page is overflowing, though, but I get the error: `Bindery: Page overflowing <div class="📖-page 📖-page-size 📖-is-overflowing">` and can see the red overflow box at the bottom of the page.

![image](https://user-images.githubusercontent.com/3684553/29425211-71a5be18-8350-11e7-8949-21cd5f43749f.png)

**Comment by teddybradford** [comment]
Oh, I see. The figcaption is overflowing.

**Comment by teddybradford** [comment]
I wonder what the best way to handle this would be? Should there be an automated fix or should this just be manual fixed?

**Comment by evnbr** [comment]
1. hm, it doesn't look like it's overflowing, I'll look into it. Unsure if the extra pages are related but they may well be.
2. In theory if your image is really tall, layout should still complete— maybe the warning is too scary-looking and doesn't need to exist.
3. It looks like you're getting creative with the margins, so maybe a smarter long-term fix would be to support different margins for different pages?

**Comment by evnbr** [comment]
@teddybradford do you have a consistent repro for this that you could send me? I wasn't able to find the pages in your screenshot on http://new.johncaserta.com/bindery.html

**Comment by teddybradford** [comment]
It appears on the spread at page 60.

Here is raw HTML output where the hidden video div wrappers are: http://new.johncaserta.com/bindery_test.html#locally-made-daily-guide

**Comment by evnbr** [comment]
Thanks. An update so far—

It looks two page are inserted, not related to the video wrappers.
- The core issue is that the image is taller than the page.
  - No pages are added when the image has a shorter set height.
  - This seems to be a fixable bug
- The overflowing is disguised because of this CSS you've added (below).
  - Only one page is added when I remove your css
  - The page was measured before bindery adds the 'continues' class, which is why it doesn't look overflowing to you after the fact.

If you're blocked on this, a workaround would be a shorter image or using a full-bleed page. We should also talk about why you need custom css and if bindery could do that work for you. (I would caution that I'm thinking of all the emoji class names as bindery-internal and could change at any time).

![image](https://user-images.githubusercontent.com/1024086/29643219-85cbe3f0-8822-11e7-9c2e-e17dd4fc691d.png)

**Comment by teddybradford** [comment]
Aha! I was using that CSS prior to you implementing the Bindery.Continuation() method and forgot to update it.

**Comment by evnbr** [comment]
Ah right — Bindery.Continuation would probably have the same issue, but at
least you wouldn't have to type emoji into your CSS :)

I believe I can fix this bug regardless of that by better handling tall
images, stay tuned

**Comment by evnbr** [comment]
This *should* be fixed in new build (v2.0.0-alpha.5), let me know if it works

**Comment by evnbr** [comment]
Seems to be resolved
